trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'release'

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Restore and Build"
    steps:
    - task: NuGetCommand@2
      displayName: "Restore NuGet Packages"
      inputs:        
        restoreSolution: '**/*.sln'
    - task : VSBuild@1
      displayName: "Build .NET Framework 4.8 Project"
      inputs :
        solution: '**/*.sln'
        msbuildArgs: '/p:Configuration=$(buildConfiguration)'
        platform: 'Any CPU'
        configuration: 'Release'
        
       


