trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'release'

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Restore and Build"
    steps:
    - task: NuGetCommand@2
      displayName: "Restore NuGet Packages"
      inputs:        
        restoreSolution: '**/*.sln'
    - task : VSBuild@1
      displayName: "Build .NET Framework 4.8 Project"
      inputs :
        solution: '**/*.sln'        
        msbuildArgs: >
          /p:Configuration=Release
          /p:DeployOnBuild=true
          /p:WebPublishMethod=FileSystem
          /p:publishUrl=$(Build.ArtifactStagingDirectory)
        platform: 'Any CPU'
        configuration: 'Release'
    - task: ArchiveFiles@2
      displayName: "ArchiveFiles@2"   
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: "zip"
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
               
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: "Deploy to Azure app service"  
  dependsOn: Build
  jobs:
    - job: Deployjob
      steps:
        - task: DownloadBuildArtifacts@0
          displayName: "Downloading Build Artifacts"
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: AzureWebApp@1
          displayName: "Deploy to Azure App Service"
          inputs:
            azureSubscription: 'Dev-Azure-Connection'
            appName: 'app-csnmc-dev02-paymentapi'
            appType: webApp
            package: '$(System.ArtifactsDirectory)/drop/app.zip'
          
       
        
       
        
        
        
       


